{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import datetime as dt\n",
    "import sqlalchemy\n",
    "from sqlalchemy.ext.automap import automap_base\n",
    "from sqlalchemy.orm import Session\n",
    "from sqlalchemy import create_engine, func\n",
    "from flask import Flask, jsonify\n",
    "\n",
    "engine = create_engine(\"sqlite:///Resources/hawaii.sqlite\", connect_args={'check_same_thread': False})\n",
    "\n",
    "\n",
    "Base = automap_base()\n",
    "Base.prepare(engine, reflect=True)\n",
    "Base.classes.keys()\n",
    "\n",
    "Measurement = Base.classes.measurement\n",
    "Station = Base.classes.station\n",
    "\n",
    "session = Session(engine)\n",
    "\n",
    "#weather app\n",
    "app = Flask(__name__)\n",
    "\n",
    "\n",
    "latest_date = (session.query(Measurement.date)\n",
    "                .order_by(Measurement.date.desc())\n",
    "                .first())\n",
    "latest_date = list(np.ravel(latest_date))[0]\n",
    "\n",
    "latest_date = dt.datetime.strptime(latest_date, '%Y-%m-%d')\n",
    "latest_year = int(dt.datetime.strftime(latest_date, '%Y'))\n",
    "latest_month = int(dt.datetime.strftime(latest_date, '%m'))\n",
    "latest_day = int(dt.datetime.strftime(latest_date, '%d'))\n",
    "\n",
    "year_before = dt.date(latest_year, latest_month, latest_day) - dt.timedelta(days=365)\n",
    "year_before = dt.datetime.strftime(year_before, '%Y-%m-%d')\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "@app.route(\"/\")\n",
    "def home():\n",
    "    return (f\"Welcome to Surf's Up!: Hawai'i Climate API<br/>\"\n",
    "            f\"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<br/>\"\n",
    "            f\"Available Routes:<br/>\"\n",
    "            f\"/api/v1.0/stations ~~~~~ a list of all weather observation stations<br/>\"\n",
    "            f\"/api/v1.0/precipitaton ~~ the latest year of preceipitation data<br/>\"\n",
    "            f\"/api/v1.0/temperature ~~ the latest year of temperature data<br/>\"\n",
    "            f\"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<br/>\"\n",
    "            f\"~~~ datesearch (yyyy-mm-dd)<br/>\"\n",
    "            f\"/api/v1.0/datesearch/2015-05-30  ~~~~~~~~~~~ low, high, and average temp for date given and each date after<br/>\"\n",
    "            f\"/api/v1.0/datesearch/2015-05-30/2016-01-30 ~~ low, high, and average temp for date given and each date up to and including end date<br/>\"\n",
    "            f\"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<br/>\"\n",
    "            f\"~ data available from 2010-01-01 to 2017-08-23 ~<br/>\"\n",
    "            f\"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\")\n",
    "\n",
    "@app.route(\"/api/v1.0/stations\")\n",
    "def stations():\n",
    "    results = session.query(Station.name).all()\n",
    "    all_stations = list(np.ravel(results))\n",
    "    return jsonify(all_stations)\n",
    "\n",
    "@app.route(\"/api/v1.0/precipitaton\")\n",
    "def precipitation():\n",
    "    \n",
    "    results = (session.query(Measurement.date, Measurement.prcp, Measurement.station)\n",
    "                      .filter(Measurement.date > year_before)\n",
    "                      .order_by(Measurement.date)\n",
    "                      .all())\n",
    "    \n",
    "    precip_data = []\n",
    "    for result in results:\n",
    "        precip_dict = {result.date: result.prcp, \"Station\": result.station}\n",
    "        precip_data.append(precip_dict)\n",
    "\n",
    "    return jsonify(precip_data)\n",
    "\n",
    "@app.route(\"/api/v1.0/temperature\")\n",
    "def temperature():\n",
    "\n",
    "    results = (session.query(Measurement.date, Measurement.tobs, Measurement.station)\n",
    "                      .filter(Measurement.date > year_before)\n",
    "                      .order_by(Measurement.date)\n",
    "                      .all())\n",
    "\n",
    "    temp_data = []\n",
    "    for result in results:\n",
    "        temp_dict = {result.date: result.tobs, \"Station\": result.station}\n",
    "        temp_data.append(temp_dict)\n",
    "\n",
    "    return jsonify(temp_data)\n",
    "\n",
    "@app.route('/api/v1.0/datesearch/<startDate>')\n",
    "def start(start_date):\n",
    "    sel = [Measurement.date, func.min(Measurement.tobs), func.avg(Measurement.tobs), func.max(Measurement.tobs)]\n",
    "\n",
    "    results =  (session.query(*sel)\n",
    "                       .filter(func.strftime(\"%Y-%m-%d\", Measurement.date) >= start_date)\n",
    "                       .group_by(Measurement.date)\n",
    "                       .all())\n",
    "\n",
    "    dates = []                       \n",
    "    for result in results:\n",
    "        date_dict = {}\n",
    "        date_dict[\"Date\"] = result[0]\n",
    "        date_dict[\"Low Temp\"] = result[1]\n",
    "        date_dict[\"Avg Temp\"] = result[2]\n",
    "        date_dict[\"High Temp\"] = result[3]\n",
    "        dates.append(date_dict)\n",
    "    return jsonify(dates)\n",
    "\n",
    "@app.route('/api/v1.0/datesearch/<startDate>/<endDate>')\n",
    "def start_end(start_date, end_date):\n",
    "    sel = [Measurement.date, func.min(Measurement.tobs), func.avg(Measurement.tobs), func.max(Measurement.tobs)]\n",
    "\n",
    "    results =  (session.query(*sel)\n",
    "                       .filter(func.strftime(\"%Y-%m-%d\", Measurement.date) >= start_date)\n",
    "                       .filter(func.strftime(\"%Y-%m-%d\", Measurement.date) <= end_date)\n",
    "                       .group_by(Measurement.date)\n",
    "                       .all())\n",
    "\n",
    "    dates = []                       \n",
    "    for result in results:\n",
    "        date_dict = {}\n",
    "        date_dict[\"Date\"] = result[0]\n",
    "        date_dict[\"Low Temp\"] = result[1]\n",
    "        date_dict[\"Avg Temp\"] = result[2]\n",
    "        date_dict[\"High Temp\"] = result[3]\n",
    "        dates.append(date_dict)\n",
    "    return jsonify(dates)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(debug=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
